### PR TITLE
Fix MT Dashboard Bugs (14 + 16)

### LINKED ISSUE #194: [MT] Dashboard Bugs
- Address [Bug #14](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.8g9l8hu92rcx)
- Address [Bug #16](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.mn92cx7xlql5)
- Include "all cycles" as an option on the MT dashboard

Possibly also address Bug #9 ? Might be fixed when 14/16 are fixed though

### PR DESCRIPTION
**Pull request by ctc-devops**
- Address [Bug #14](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.8g9l8hu92rcx)
- Address [Bug #16](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.mn92cx7xlql5)
- Include "all cycles" as an option on the MT dashboard

Possibly also address Bug #9 ? Might be fixed when 14/16 are fixed though
closes #194

### CODE REVIEW

File: src/pages/master-teacher/master-teacher.jsx [hunk 1]
```diff
@@ -196,7 +196,8 @@ const MasterTeacherView = ({ cookies }) => {
       if (data.length === 0) {
         return;
       }
-
+      const tData = await TLPBackend.get(`/teachers/${teacherId}`);
+      console.log(tData.data);
```
Comment (ctc-devops) [inline src/pages/master-teacher/master-teacher.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/pages/master-teacher/master-teacher.jsx [hunk 2]
```diff
@@ -191,12 +191,17 @@ const MasterTeacherView = ({ cookies }) => {
     async function fetchTeacherData() {
       const allStudentData = await TLPBackend.get(`/student-groups/master-teacher/${teacherId}`);
       // all unfiltered data for the MT to user for filtering later
+      // let { data } = allStudentData;
       const { data } = allStudentData;
       setAllData(data);
+      console.log('data');
```
Comment (ctc-devops) [inline src/pages/master-teacher/master-teacher.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/pages/master-teacher/master-teacher.jsx [hunk 3]
```diff
@@ -191,12 +191,17 @@ const MasterTeacherView = ({ cookies }) => {
...
+      console.log(data);
```
Comment (ctc-devops) [inline src/pages/master-teacher/master-teacher.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by anikait-rao — APPROVED** [review]
