### PR TITLE
nav-bar-bug-fix

### LINKED ISSUE #109: [General] Nav Bar Bug Fixes
Designed by: Meredith (review with her)
Due Friday 4/15

Figma: https://www.figma.com/file/O2igPzMS1fZPzjmOxlo6Mc/TLP-Wireframes?node-id=538%3A23322

[General]
- Currently, the component rendering is route-based rather than role-based. Make it so that the Nav Bar renders based on role (MT or Admin) rather than route.
- The Nav Bar also is individually on each "page" as opposed to being in index.jsx (and only displaying for specific roles). Add nav bar to all MT/admin roles within index.jsx (all non-public pages), and remove it from the individual pages on the website.

[Admin]:
- Move Settings to the left of the bar and add a "Help" link.

### PR DESCRIPTION
**Pull request by ctc-devops**
Designed by: Meredith (review with her)
Due Friday 4/15

Figma: https://www.figma.com/file/O2igPzMS1fZPzjmOxlo6Mc/TLP-Wireframes?node-id=538%3A23322

[General]
- Currently, the component rendering is route-based rather than role-based. Make it so that the Nav Bar renders based on role (MT or Admin) rather than route.
- The Nav Bar also is individually on each "page" as opposed to being in index.jsx (and only displaying for specific roles). Add nav bar to all MT/admin roles within index.jsx (all non-public pages), and remove it from the individual pages on the website.

[Admin]:
- Move Settings to the left of the bar and add a "Help" link.
closes #109

### CODE REVIEW

File: src/components/NavigationBar/NavigationBar.jsx [hunk 1]
```diff
@@ -21,80 +21,91 @@ const NavigationBar = ({ cookies }) => {
...
-              {errorMessage && <p>{errorMessage}</p>}
-            </Nav>
-          </Navbar.Collapse>
-        </Container>
-      </Navbar>
-    );
-  }
+  const searchForStudent = event => {
+    if (event.key === 'Enter') {
+      console.log('Need to implement search feature.');
```
Comment (ctc-devops) [inline src/components/NavigationBar/NavigationBar.jsx:26]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by anikait-rao — APPROVED** [review]
looks good
