### PR TITLE
student-page-flow-and-bugs

### LINKED ISSUE #126: [MT] Student Page Flow and Bugs
On the student page:

1. Connect the links at the bottom of the page to the student's assessment card, attitude survey, and student group pages.
2. Add a column for "gender" with the options "male", "female", and "non-specified".
3. Change the "ethnicity" dropdown so that multiple ethnicities can be selected.

### PR DESCRIPTION
**Pull request by ctc-devops**
On the student page:

1. Connect the links at the bottom of the page to the student's assessment card, attitude survey, and student group pages.
2. Add a column for "gender" with the options "male", "female", and "non-specified".
3. Change the "ethnicity" dropdown so that multiple ethnicities can be selected.
closes #126

### CODE REVIEW

File: src/index.jsx [hunk 1]
```diff
@@ -125,7 +125,7 @@ ReactDOM.render(
                 <ProtectedRoute
                   Component={StudentView}
                   redirectPath="/access-denied"
-                  roles={[USER_ROLE]}
+                  roles={[ADMIN_ROLE, USER_ROLE]}
```
Comment (anikait-rao) [inline src/index.jsx]: Make it only USER_ROLE. If you need a MT account some credentials are

email: hang.m.cao@gmail.com
pass: Hello82!

File: src/pages/student/student.jsx [hunk 2]
```diff
@@ -144,13 +151,17 @@ const StudentView = () => {
...
-              'white',
-              'black',
-              'asian',
-              'latinx',
-              'american indian or alaska native',
-              'non-specified',
+              { value: 'white', label: 'white' },
+              { value: 'black', label: 'black' },
+              { value: 'asian', label: 'asian' },
+              { value: 'latinx', label: 'latinx' },
```
Comment (anikait-rao) [inline src/pages/student/student.jsx]: nitpick - can you capitalize ethnicity and gender values on the frontend. you will still need to pass in lowercase values to the backend since that's how we store it.

File: src/pages/student/student.jsx [hunk 3]
```diff
@@ -144,13 +151,17 @@ const StudentView = () => {
...
+              {
+                value: 'american indian or alaska native',
+                label: 'american indian or alaska native',
+              },
+              { value: 'non-specified', label: 'non-specified' },
             ],
+            genderOptions: ['male', 'female', 'non-specified'],
             studentGroups: [...resOptions.data],
```
Comment (anikait-rao) [inline src/pages/student/student.jsx]: Check recent tlp-general thread for whether or not to refine this data more

**Review by anikait-rao — COMMENTED** [review]
see comments

**Review by anikait-rao — APPROVED** [review]
good job
