### PR TITLE
student-group-view-modal-bugs

### LINKED ISSUE #173: [MT] Student Group View/Edit Student Group Modal Refactor/Bug
1. Condense the code in [lines 40-74](https://github.com/ctc-uci/the-literacy-project-frontend/blob/554680203f913598277107cf5df31cd606572f64/src/pages/student-group-view/student-group-view.jsx#L40) of student-group-view.jsx to use just one backend request (I think `/student-groups/${studentGroupId}` should give you all the information you need including the site info).
2. Address [Bug #15](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.lmeoi9lqako9)

### PR DESCRIPTION
**Pull request by ctc-devops**
1. Condense the code in [lines 40-74](https://github.com/ctc-uci/the-literacy-project-frontend/blob/554680203f913598277107cf5df31cd606572f64/src/pages/student-group-view/student-group-view.jsx#L40) of student-group-view.jsx to use just one backend request (I think `/student-groups/${studentGroupId}` should give you all the information you need including the site info).
2. Address [Bug #15](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.lmeoi9lqako9)
closes #173

### CODE REVIEW

**Review by anikait-rao — CHANGES_REQUESTED** [review]
1. The list of possible students that can be added in both the Create and Edit Student Group modals needs to only be students who do not have a student group - their groupId would be `null`.
2. Can we have it so that when they press "Save" the student group page reloads

File: src/pages/student-group-view/student-group-view.jsx [hunk 1]
```diff
@@ -83,7 +79,18 @@ const StudentGroupView = () => {
       setTestScores({});
       setError(error);
     }
-  }, [siteId]);
+    console.log('request');
```
Comment (ctc-devops) [inline src/pages/student-group-view/student-group-view.jsx:82]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/pages/student-group-view/student-group-view.jsx [hunk 2]
```diff
@@ -83,7 +79,18 @@ const StudentGroupView = () => {
...
+    console.log(groupUpdated);
```
Comment (ctc-devops) [inline src/pages/student-group-view/student-group-view.jsx:83]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by anikait-rao — APPROVED** [review]
looks good
